## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow import keras


# import keras
# from keras.layers import Dense

#  Import and read the charity_data.csv.
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

ImportError: cannot import name 'keras' from 'tensorflow' (unknown location)

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns= ['EIN', 'NAME'], inplace= True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
app_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_counts[app_type_counts < 1000].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_vc = application_df['CLASSIFICATION'].value_counts()
classification_vc

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_vc[classification_vc> 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_vc[classification_vc<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_to_dummies = pd.get_dummies(application_df)
boolean_cols = application_to_dummies.select_dtypes(include='bool').columns
application_to_dummies[boolean_cols] = application_to_dummies[boolean_cols].astype(int)
application_to_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
X = application_to_dummies.drop(["IS_SUCCESSFUL"],axis=1)
y = application_to_dummies["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

Model#1

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn1 = keras.models.Sequential()

# First hidden layer
nn1.add(keras.layers.Dense(units=80, input_dim=len(X_train_scaled[0]), activation="relu"))

# Second hidden layer
nn1.add(keras.layers.Dense(units=30, activation="tanh"))

# Output layer
nn1.add(keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn1.summary()

AttributeError: module 'tensorflow' has no attribute 'keras'

In [ ]:
# Compile the model
nn1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

NameError: name 'nn1' is not defined

In [ ]:
# Train the model
nn1.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5729 - accuracy: 0.7162
Epoch 2/100
804/804 [==============================] - 1s 991us/step - loss: 0.5593 - accuracy: 0.7268
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7287
Epoch 4/100
804/804 [==============================] - 1s 961us/step - loss: 0.5546 - accuracy: 0.7303
Epoch 5/100
804/804 [==============================] - 1s 959us/step - loss: 0.5532 - accuracy: 0.7285
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5524 - accuracy: 0.7302
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5512 - accuracy: 0.7301
Epoch 8/100
804/804 [==============================] - 1s 975us/step - loss: 0.5510 - accuracy: 0.7314
Epoch 9/100
804/804 [==============================] - 1s 948us/step - loss: 0.5502 - accuracy: 0.7324
Epoch 10/100
804/804 [==============================] - 1s 958us/step - loss: 0.5498 - accuracy: 0.7311
Epoch 11/100
804/804 [==============================] - 1s 968us/step - loss: 0.5494 - accuracy: 0.7322
Epoch 12/100
804/804 [==============================] - 1s 955us/step - loss: 0.5486 - accuracy: 0.7329
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7336
Epoch 14/100
804/804 [==============================] - 1s 984us/step - loss: 0.5482 - accuracy: 0.7333
Epoch 15/100
804/804 [==============================] - 1s 963us/step - loss: 0.5476 - accuracy: 0.7339
Epoch 16/100
804/804 [==============================] - 1s 960us/step - loss: 0.5474 - accuracy: 0.7333
Epoch 17/100
804/804 [==============================] - 1s 941us/step - loss: 0.5470 - accuracy: 0.7340
Epoch 18/100
804/804 [==============================] - 1s 947us/step - loss: 0.5469 - accuracy: 0.7336
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7336
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7346
Epoch 21/100
804/804 [==============================] - 1s 975us/step - loss: 0.5460 - accuracy: 0.7342
Epoch 22/100
804/804 [==============================] - 1s 955us/step - loss: 0.5457 - accuracy: 0.7353
Epoch 23/100
804/804 [==============================] - 1s 960us/step - loss: 0.5455 - accuracy: 0.7339
Epoch 24/100
804/804 [==============================] - 1s 952us/step - loss: 0.5453 - accuracy: 0.7350
Epoch 25/100
804/804 [==============================] - 1s 961us/step - loss: 0.5450 - accuracy: 0.7360
Epoch 26/100
804/804 [==============================] - 1s 954us/step - loss: 0.5450 - accuracy: 0.7355
Epoch 27/100
804/804 [==============================] - 1s 951us/step - loss: 0.5446 - accuracy: 0.7357
Epoch 28/100
804/804 [==============================] - 1s 974us/step - loss: 0.5444 - accuracy: 0.7350
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7364
Epoch 30/100
804/804 [==============================] - 1s 943us/step - loss: 0.5443 - accuracy: 0.7359
Epoch 31/100
804/804 [==============================] - 1s 932us/step - loss: 0.5440 - accuracy: 0.7357
Epoch 32/100
804/804 [==============================] - 1s 937us/step - loss: 0.5439 - accuracy: 0.7364
Epoch 33/100
804/804 [==============================] - 1s 938us/step - loss: 0.5438 - accuracy: 0.7369
Epoch 34/100
804/804 [==============================] - 1s 933us/step - loss: 0.5438 - accuracy: 0.7360
Epoch 35/100
804/804 [==============================] - 1s 945us/step - loss: 0.5434 - accuracy: 0.7370
Epoch 36/100
804/804 [==============================] - 1s 984us/step - loss: 0.5435 - accuracy: 0.7362
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7364
Epoch 38/100
804/804 [==============================] - 1s 983us/step - loss: 0.5430 - accuracy: 0.7365
Epoch 39/100
804/804 [==============================] - 1s 912us/step - loss: 0.5428 - accuracy: 0.7358
Epoch 40/100
804/804 [==============================] - 1s 916us/step - loss: 0.5428 - accuracy: 0.7370
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7366
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7373
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7371
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7366
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7354
Epoch 46/100
804/804 [==============================] - 1s 962us/step - loss: 0.5423 - accuracy: 0.7371
Epoch 47/100
804/804 [==============================] - 1s 939us/step - loss: 0.5418 - accuracy: 0.7374
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7369
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7374
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7371
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7374
Epoch 52/100
804/804 [==============================] - 1s 962us/step - loss: 0.5414 - accuracy: 0.7383
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7377
Epoch 54/100
804/804 [==============================] - 1s 948us/step - loss: 0.5410 - accuracy: 0.7380
Epoch 55/100
804/804 [==============================] - 1s 984us/step - loss: 0.5413 - accuracy: 0.7373
Epoch 56/100
804/804 [==============================] - 1s 923us/step - loss: 0.5409 - accuracy: 0.7375
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7373
Epoch 58/100
804/804 [==============================] - 1s 964us/step - loss: 0.5409 - accuracy: 0.7375
Epoch 59/100
804/804 [==============================] - 1s 915us/step - loss: 0.5409 - accuracy: 0.7374
Epoch 60/100
804/804 [==============================] - 1s 917us/step - loss: 0.5410 - accuracy: 0.7367
Epoch 61/100
804/804 [==============================] - 1s 898us/step - loss: 0.5409 - accuracy: 0.7373
Epoch 62/100
804/804 [==============================] - 1s 895us/step - loss: 0.5408 - accuracy: 0.7376
Epoch 63/100
804/804 [==============================] - 1s 892us/step - loss: 0.5406 - accuracy: 0.7379
Epoch 64/100
804/804 [==============================] - 1s 890us/step - loss: 0.5406 - accuracy: 0.7383
Epoch 65/100
804/804 [==============================] - 1s 908us/step - loss: 0.5408 - accuracy: 0.7371
Epoch 66/100
804/804 [==============================] - 1s 938us/step - loss: 0.5405 - accuracy: 0.7372
Epoch 67/100
804/804 [==============================] - 1s 894us/step - loss: 0.5406 - accuracy: 0.7375
Epoch 68/100
804/804 [==============================] - 1s 877us/step - loss: 0.5407 - accuracy: 0.7381
Epoch 69/100
804/804 [==============================] - 1s 873us/step - loss: 0.5403 - accuracy: 0.7385
Epoch 70/100
804/804 [==============================] - 1s 869us/step - loss: 0.5404 - accuracy: 0.7384
Epoch 71/100
804/804 [==============================] - 1s 882us/step - loss: 0.5401 - accuracy: 0.7371
Epoch 72/100
804/804 [==============================] - 1s 880us/step - loss: 0.5404 - accuracy: 0.7380
Epoch 73/100
804/804 [==============================] - 1s 874us/step - loss: 0.5403 - accuracy: 0.7382
Epoch 74/100
804/804 [==============================] - 1s 926us/step - loss: 0.5403 - accuracy: 0.7382
Epoch 75/100
804/804 [==============================] - 1s 871us/step - loss: 0.5398 - accuracy: 0.7381
Epoch 76/100
804/804 [==============================] - 1s 874us/step - loss: 0.5402 - accuracy: 0.7383
Epoch 77/100
804/804 [==============================] - 1s 883us/step - loss: 0.5404 - accuracy: 0.7378
Epoch 78/100
804/804 [==============================] - 1s 871us/step - loss: 0.5404 - accuracy: 0.7378
Epoch 79/100
804/804 [==============================] - 1s 885us/step - loss: 0.5400 - accuracy: 0.7378
Epoch 80/100
804/804 [==============================] - 1s 857us/step - loss: 0.5399 - accuracy: 0.7374
Epoch 81/100
804/804 [==============================] - 1s 861us/step - loss: 0.5400 - accuracy: 0.7379
Epoch 82/100
804/804 [==============================] - 1s 858us/step - loss: 0.5396 - accuracy: 0.7381
Epoch 83/100
804/804 [==============================] - 1s 911us/step - loss: 0.5396 - accuracy: 0.7391
Epoch 84/100
804/804 [==============================] - 1s 861us/step - loss: 0.5399 - accuracy: 0.7391
Epoch 85/100
804/804 [==============================] - 1s 862us/step - loss: 0.5395 - accuracy: 0.7388
Epoch 86/100
804/804 [==============================] - 1s 862us/step - loss: 0.5393 - accuracy: 0.7383
Epoch 87/100
804/804 [==============================] - 1s 867us/step - loss: 0.5398 - accuracy: 0.7377
Epoch 88/100
804/804 [==============================] - 1s 863us/step - loss: 0.5398 - accuracy: 0.7389
Epoch 89/100
804/804 [==============================] - 1s 855us/step - loss: 0.5397 - accuracy: 0.7378
Epoch 90/100
804/804 [==============================] - 1s 912us/step - loss: 0.5394 - accuracy: 0.7388
Epoch 91/100
804/804 [==============================] - 1s 851us/step - loss: 0.5394 - accuracy: 0.7390
Epoch 92/100
804/804 [==============================] - 1s 859us/step - loss: 0.5398 - accuracy: 0.7385
Epoch 93/100
804/804 [==============================] - 1s 884us/step - loss: 0.5397 - accuracy: 0.7382
Epoch 94/100
804/804 [==============================] - 1s 871us/step - loss: 0.5399 - accuracy: 0.7383
Epoch 95/100
804/804 [==============================] - 1s 868us/step - loss: 0.5397 - accuracy: 0.7386
Epoch 96/100
804/804 [==============================] - 1s 865us/step - loss: 0.5395 - accuracy: 0.7382
Epoch 97/100
804/804 [==============================] - 1s 868us/step - loss: 0.5397 - accuracy: 0.7385
Epoch 98/100
804/804 [==============================] - 1s 916us/step - loss: 0.5393 - accuracy: 0.7391
Epoch 99/100
804/804 [==============================] - 1s 862us/step - loss: 0.5398 - accuracy: 0.7378
Epoch 100/100
804/804 [==============================] - 1s 860us/step - loss: 0.5394 - accuracy: 0.7386

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5582 - accuracy: 0.7305 - 291ms/epoch - 1ms/step
Loss: 0.5581920146942139, Accuracy: 0.7304956316947937

In [ ]:
# Export our model to HDF5 file
nn1.save('AlphabetSoupCharity1.h5')

ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.

Model#2

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn2 = tf.keras.models.Sequential()

# First hidden layer
nn2.add(tf.keras.layers.Dense(units=120, input_dim=len(X_train_scaled[0]), activation="relu"))

# Second hidden layer
nn2.add(tf.keras.layers.Dense(units=80, activation="tanh"))

# Third hidden layer
nn2.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn2.summary()

In [ ]:
# Compile the model
nn2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
nn2.fit(X_train_scaled,y_train,epochs=100)

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Export our model to HDF5 file
nn2.save('AlphabetSoupCharity2.h5')

Model#3

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn3 = tf.keras.models.Sequential()

# First hidden layer
nn3.add(tf.keras.layers.Dense(units=300, input_dim=len(X_train_scaled[0]), activation="relu"))

# Second hidden layer
nn3.add(tf.keras.layers.Dense(units=100, activation="tanh"))

# Third hidden layer
nn3.add(tf.keras.layers.Dense(units=50, activation="relu"))

# Fourth hidden layer
nn3.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn3.summary()

In [ ]:
# Compile the model
nn3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
nn3.fit(X_train_scaled,y_train,epochs=100)

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Export our model to HDF5 file
nn3.save('AlphabetSoupCharity3.h5')